/* Database schema to keep the structure of entire database. */
CREATE DATABASE vet_clinic;

CREATE TABLE animals (
    id int NOT NULL PRIMARY KEY,
    name varchar(100),
    date_of_birth date,
    escape_attemps int,
    neutered boolean,
    weight_kg decimal,
);

ALTER table animals 
    ADD species varchar(100);


CREATE table owners (
    id int NOT NULL PRIMARY KEY,
    full_name varchar(50),
    age int
);

CREATE table species (
    id int NOT NULL PRIMARY KEY,
    name varchar(50)
);

ALTER TABLE animals 
    ALTER id ADD GENERATED BY DEFAULT as IDENTITY (start with 12);

ALTER TABLE animals 
    DROP COLUMN species;

ALTER TABLE animals
    ADD COLUMN species_id int REFERENCES species(id) ON DELETE cascade;

ALTER TABLE animals 
    ADD COLUMN owner_id int REFERENCES owners(id) ON DELETE cascade;

CREATE TABLE vets (
    id int NOT NULL GENERATED by DEFAULT as IDENTITY (start with 1) PRIMARY KEY,
    name varchar(50),
    age int,
    date_of_graduation date
);

CREATE TABLE specializations (
    species_id int NOT NULL REFERENCES species(id) ON DELETE cascade,
    vet_id int NOT NULL REFERENCES vets(id) ON DELETE cascade,
    PRIMARY KEY (species_id, vet_id)
);

CREATE TABLE visits (
    animal_id int NOT NULL REFERENCES animals(id) ON DELETE cascade,
    vet_id int NOT NULL REFERENCES vets(id) ON DELETE cascade,
    date_of_visit date NOT NULL,
    PRIMARY KEY(animal_id, vet_id, date_of_visit)
);